### PR TITLE
Fixed issue with generate params and midi output params

### PR DESCRIPTION
**Pull request by camiblanch**
Without this fix I was unable to get anything other than uncaught errors using python 2.7. Once I fixed the params, everything worked smoothly.

### CODE REVIEW

**Comment by almostimplemented** [comment]
Closes #2

**Comment by gnestor** [comment]
This fixes https://github.com/googlecreativelab/aiexperiments-ai-duet/issues/2 for me!

**Comment by andrew-c-edwards** [comment]
This gets the basic code to run, but if you try to use a different RNN you'll run into problems. See discussion in #2 . A better temp fix is to move `third_party/magenta` up a level to simply `magenta` ... In there, there is an implementation of `generate` that takes a `GenerateSequenceRequest` object.

**Comment by Hdooster** [comment]
@andrew-c-edwards your fix worked as well for me (2.7), thanks!

**Pull request merged**
